<?php namespace iAmirNet\BehPardakht;

use App;
use Auth;
use Azarinweb\Minimall\Classes\Payments\DefaultPaymentGateway;
use Azarinweb\Minimall\Classes\Payments\Offline;
use Azarinweb\Minimall\Classes\Payments\PaymentGateway;
use Azarinweb\Minimall\Classes\Payments\ZarinPal;
use iAmirNet\BehPardakht\Classes\Gateway\Message\Gateway;
use iAmirNet\BehPardakht\Models\BehPardakht;
use iAmirNet\BehPardakht\Models\BehPardakhtSettings;
use Event;
use Backend;
use System\Classes\PluginBase;
use System\Classes\SettingsManager;
use Illuminate\Foundation\AliasLoader;
use Azarinweb\User\Classes\UserRedirector;
use Azarinweb\User\Models\MailBlocker;
use Azarinweb\Notify\Classes\Notifier;

class Plugin extends PluginBase
{
    /**
     * @var boolean Determine if this plugin should have elevated privileges.
     */
    public $elevated = true;

    public function pluginDetails()
    {
        return [
            'name'        => 'iamirnet.behpardakht::lang.plugin.name',
            'description' => 'iamirnet.behpardakht::lang.plugin.description',
            'author'      => 'iamirnet',
            'icon'        => 'icon-user',
            'homepage'    => 'https://iAmir.Net'
        ];
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function register()
    {
        //parent::register(); // TODO: Change the autogenerated stub
        //
    }

    public function registerPermissions()
    {
        return [
            'iamirnet.behpardakht.access_behpardakht' => [
                'tab'   => 'iamirnet.behpardakht::lang.plugin.tab',
                'label' => 'iamirnet.behpardakht::lang.plugin.access_behpardakht'
            ],
        ];
    }

    public function registerSettings()
    {
        return [
            'settings' => [
                'label'       => 'iamirnet.behpardakht::lang.behpardakht.title',
                'description' => 'iamirnet.behpardakht::lang.behpardakht.description',
                'category'    => 'iamirnet.minimall::lang.settings.gateway.title',
                'icon'        => 'icon-credit-card',
                'class'       => BehPardakhtSettings::class,
                'order'       => 700,
                'permissions' => ['iamirnet.behpardakht.access_behpardakht']
            ]
        ];
    }

    public function registerPaymentGateways()
    {
        return [
            \iAmirNet\BehPardakht\Models\BehPardakht::class => 'behpardakht',
        ];
    }
}
